import {useEffect,useRef,useState} from 'react';
let ytPromise:Promise<any>|null=null;
function loadYT(){if((window as any).YT?.Player)return Promise.resolve((window as any).YT);if(ytPromise)return ytPromise;ytPromise=new Promise(resolve=>{const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s);(window as any).onYouTubeIframeAPIReady=()=>resolve((window as any).YT)});return ytPromise}
export function VideoPlayer({room,playing,position,onPlay,onPause,onSeek}:any){const host=useRef<HTMLDivElement>(null),player=useRef<any>(null),wrap=useRef<HTMLDivElement>(null);const [progress,setProgress]=useState(position||0),[duration,setDuration]=useState(0),[quality,setQuality]=useState('auto'),[menu,setMenu]=useState(false),[controls,setControls]=useState(true);const provider=room.provider;
useEffect(()=>{setProgress(position||0)},[position]);
useEffect(()=>{let alive=true;if(provider==='youtube'){loadYT().then((YT:any)=>{if(!alive||!host.current)return;player.current=new YT.Player(host.current,{videoId:room.video_id,playerVars:{playsinline:1,controls:0,rel:0,modestbranding:1,disablekb:1},events:{onReady:(e:any)=>{setDuration(e.target.getDuration());if(playing)e.target.playVideo();},onStateChange:(e:any)=>{if(e.data===1)onPlay?.();if(e.data===2)onPause?.()}}});});}return()=>{alive=false;player.current?.destroy?.();player.current=null}},[provider,room.video_id]);
useEffect(()=>{const t=setInterval(()=>{if(player.current?.getCurrentTime){const p=player.current.getCurrentTime();setProgress(p)}},500);return()=>clearInterval(t)},[]);
useEffect(()=>{if(!player.current)return;if(playing)player.current.playVideo?.();else player.current.pauseVideo?.();},[playing]);
function seekBy(delta:number){const next=Math.max(0,Math.min(duration||Infinity,progress+delta));if(player.current?.seekTo)player.current.seekTo(next,true);else if(onSeek)onSeek(next);setProgress(next);onSeek?.(next)}
function seekTo(v:number){const next=Number(v);if(player.current?.seekTo)player.current.seekTo(next,true);setProgress(next);onSeek?.(next)}
function setQ(q:string){setQuality(q);setMenu(false);const map:any={auto:'default', '1080p':'hd1080','720p':'hd720','480p':'large'};player.current?.setPlaybackQuality?.(map[q]||'default')}
async function full(){try{if(!document.fullscreenElement)await wrap.current?.requestFullscreen?.();else await document.exitFullscreen?.()}catch{}}
const src=provider==='vk'?`https://vk.com/video_ext.php?oid=${room.video_id?.split('_')[0]}&id=${room.video_id?.split('_')[1]}&js_api=1`:provider==='drive'?`https://drive.google.com/file/d/${room.video_id}/preview`:'';
if(!provider)return <div className="empty-player"><div className="play-orb">▶</div><span>Добавь видео по ссылке</span></div>;
return <div className={`player-shell ${controls?'show-controls':''}`} ref={wrap} onMouseMove={()=>setControls(true)}>{provider==='youtube'?<div ref={host} className="video-frame"/>:<iframe className="video-frame" src={src} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen title="Wathis player"/>}<div className="tap-zone left" onDoubleClick={()=>seekBy(-10)} onClick={()=>setControls(v=>!v)}/><div className="tap-zone center" onClick={()=>playing?onPause?.():onPlay?.()}/><div className="tap-zone right" onDoubleClick={()=>seekBy(10)} onClick={()=>setControls(v=>!v)}/><div className="player-overlay"><div className="skip-hint left-hint">−10</div><div className="skip-hint right-hint">+10</div></div><div className="player-controls"><input className="seekbar" type="range" min="0" max={duration||100} step="0.1" value={Math.min(progress,duration||100)} onChange={e=>seekTo(e.target.value)}/><div className="controls-row"><button onClick={()=>seekBy(-10)}>↶ 10</button><button className="main-play" onClick={()=>playing?onPause?.():onPlay?.()}>{playing?'Ⅱ':'▶'}</button><button onClick={()=>seekBy(10)}>10 ↷</button><span className="time">{fmt(progress)} / {fmt(duration)}</span><div className="quality-wrap">{provider==='youtube'?<><button onClick={()=>setMenu(!menu)}>HD · {quality}⌄</button>{menu&&<div className="quality-menu">{['auto','1080p','720p','480p'].map(q=><button key={q} onClick={()=>setQ(q)}>{q}{q===quality?' ✓':''}</button>)}</div></>:<button className="quality-disabled" title="Качество управляется источником">HD · авто</button>}</div><button onClick={full}>⛶</button></div></div></div>}
function fmt(v:number){if(!v||!isFinite(v))return '00:00';return `${Math.floor(v/60).toString().padStart(2,'0')}:${Math.floor(v%60).toString().padStart(2,'0')}`}